spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security-demo?useUnicode=yes&charactorEncoding=utf8
    username: root
    password: root
  session:
    store-type: none
com:
  rory:
    security:
      browser:
        loginType: redirect
      code:
        image:
          length: 6
          width: 100
          url: /users/*